plugins:
  nats:
    server_url: "nats://nats:4222"
    ttl: "10m"
    refresh_interval: "30s"
    max_reconnect_attempts: 10
    reconnect_wait: "2s"
    max_bucket_watchers: 1
    root_bucket: "permit-groups-default"

services:
  authz:
    url: http://0.0.0.0:8181
