version: "2"

run:
  timeout: 10m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - errcheck
          - dupl
          - gosec
  settings:
    errcheck:
      check-type-assertions: true
    revive:
      confidence: 0.9  # Increased from 0.8 for better precision
    govet:
      disable:
        - fieldalignment  # not critical for functionality
        - shadow          # not critical for functionality
