version: '3.8'

services:
  nats:
    image: nats:2.10-alpine
    container_name: nats-server
    command: >
      --jetstream
      --store_dir=/data
      --port=4222
      --http_port=8222
    ports:
      - "4222:4222"   # NATS client port
      - "8222:8222"   # HTTP monitoring port
    volumes:
      - nats_data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - nats-net

  nats-ui:
    image: ghcr.io/nats-nui/nui:latest
    depends_on:
      nats:
        condition: service_healthy
    volumes:
      - nats_data:/db
    ports:
      - "31311:31311"
    networks:
      - nats-net

  # NATS CLI for testing and setup
  nats-cli:
    image: natsio/nats-box:latest
    container_name: nats-cli-test
    depends_on:
      nats:
        condition: service_healthy
    entrypoint: /bin/sh
    command: -c "sleep infinity"
    environment:
      - NATS_URL=nats://nats:4222
    networks:
      - nats-net

  # Test data setup service
  nats-setup:
    image: natsio/nats-box:latest
    container_name: nats-setup
    depends_on:
      nats:
        condition: service_healthy
    volumes:
      - ./test-data:/test-data
    environment:
      - NATS_URL=nats://nats:4222
    command: >
      /bin/sh -c "
        echo 'Setting up NATS K/V buckets for UUID-based groups (each group UUID = separate bucket)...';
        
        # Create individual buckets for each group UUID
        echo 'Creating group UUID buckets...';
        nats kv add 550e8400-e29b-41d4-a716-446655440000 --replicas=1 --history=10 --ttl=12h;
        nats kv add 660e8400-e29b-41d4-a716-446655440001 --replicas=1 --history=10 --ttl=12h;
        nats kv add 770e8400-e29b-41d4-a716-446655440002 --replicas=1 --history=10 --ttl=12h;
        
        # Create default bucket for non-group data (users)
        nats kv add permit-groups-default --replicas=1 --history=10 --ttl=12h;
        
        echo 'All buckets created successfully';
        
        echo 'Populating Administrators group (bucket: 550e8400-e29b-41d4-a716-446655440000)...';
        # In this bucket, store data without the groups.{uuid} prefix since the bucket IS the group
        nats kv put 550e8400-e29b-41d4-a716-446655440000 metadata '{\"id\":\"550e8400-e29b-41d4-a716-446655440000\",\"name\":\"Administrators\",\"description\":\"System administrators group\",\"created_at\":\"2024-01-15T10:00:00Z\"}';
        nats kv put 550e8400-e29b-41d4-a716-446655440000 members.123e4567-e89b-12d3-a456-426614174000 '{\"user_id\":\"123e4567-e89b-12d3-a456-426614174000\",\"joined_at\":\"2024-01-15T10:05:00Z\",\"role\":\"admin\"}';
        nats kv put 550e8400-e29b-41d4-a716-446655440000 members.234e5678-e89b-12d3-a456-426614174001 '{\"user_id\":\"234e5678-e89b-12d3-a456-426614174001\",\"joined_at\":\"2024-01-15T10:10:00Z\",\"role\":\"member\"}';
        nats kv put 550e8400-e29b-41d4-a716-446655440000 permissions.perm-admin-api '{\"id\":\"perm-admin-api\",\"resource\":\"api\",\"action\":\"admin\",\"effect\":\"allow\"}';
        nats kv put 550e8400-e29b-41d4-a716-446655440000 permissions.perm-admin-users '{\"id\":\"perm-admin-users\",\"resource\":\"users\",\"action\":\"manage\",\"effect\":\"allow\"}';
        
        echo 'Populating Developers group (bucket: 660e8400-e29b-41d4-a716-446655440001)...';
        nats kv put 660e8400-e29b-41d4-a716-446655440001 metadata '{\"id\":\"660e8400-e29b-41d4-a716-446655440001\",\"name\":\"Developers\",\"description\":\"Development team group\",\"created_at\":\"2024-01-15T10:30:00Z\"}';
        nats kv put 660e8400-e29b-41d4-a716-446655440001 members.345e6789-e89b-12d3-a456-426614174002 '{\"user_id\":\"345e6789-e89b-12d3-a456-426614174002\",\"joined_at\":\"2024-01-15T10:35:00Z\",\"role\":\"lead\"}';
        nats kv put 660e8400-e29b-41d4-a716-446655440001 members.234e5678-e89b-12d3-a456-426614174001 '{\"user_id\":\"234e5678-e89b-12d3-a456-426614174001\",\"joined_at\":\"2024-01-15T10:40:00Z\",\"role\":\"member\"}';
        nats kv put 660e8400-e29b-41d4-a716-446655440001 permissions.perm-dev-code '{\"id\":\"perm-dev-code\",\"resource\":\"code\",\"action\":\"write\",\"effect\":\"allow\"}';
        nats kv put 660e8400-e29b-41d4-a716-446655440001 permissions.perm-dev-deploy '{\"id\":\"perm-dev-deploy\",\"resource\":\"deployment\",\"action\":\"deploy\",\"effect\":\"allow\"}';
        
        echo 'Populating ReadOnly Users group (bucket: 770e8400-e29b-41d4-a716-446655440002)...';
        nats kv put 770e8400-e29b-41d4-a716-446655440002 metadata '{\"id\":\"770e8400-e29b-41d4-a716-446655440002\",\"name\":\"ReadOnly Users\",\"description\":\"Read-only access group\",\"created_at\":\"2024-01-15T11:00:00Z\"}';
        nats kv put 770e8400-e29b-41d4-a716-446655440002 members.456e7890-e89b-12d3-a456-426614174003 '{\"user_id\":\"456e7890-e89b-12d3-a456-426614174003\",\"joined_at\":\"2024-01-15T11:05:00Z\",\"role\":\"member\"}';
        nats kv put 770e8400-e29b-41d4-a716-446655440002 permissions.perm-readonly-data '{\"id\":\"perm-readonly-data\",\"resource\":\"data\",\"action\":\"read\",\"effect\":\"allow\"}';
        
        echo 'Populating default bucket with user group assignments...';
        # User-group assignments go to the default bucket since they are not group-specific
        nats kv put permit-groups-default metadata '{\"id\":\"permit-groups-default\",\"name\":\"Default Group\",\"description\":\"Default group for non-grouped data\",\"created_at\":\"2024-01-15T10:00:00Z\"}';

        nats kv put permit-groups-default users '[\"550e8400-e29b-41d4-a716-446655440000\",\"660e8400-e29b-41d4-a716-446655440001\"]';
        # nats kv put permit-groups-default users.234e5678-e89b-12d3-a456-426614174001.groups '[\"150e8400-e29b-41d4-a716-446655440000\",\"660e8400-e29b-41d4-a716-446655440001\"]';
        # nats kv put permit-groups-default users.345e6789-e89b-12d3-a456-426614174002.groups '[\"160e8400-e29b-41d4-a716-446655440001\"]';
        # nats kv put permit-groups-default users.456e7890-e89b-12d3-a456-426614174003.groups '[\"170e8400-e29b-41d4-a716-446655440002\"]';
        # nats kv put permit-groups-default users.123e4567-e89b-12d3-a456-426614174000.groups '[\"150e8400-e29b-41d4-a716-446655440000\"]';
        
        echo 'Test data added successfully';
        echo '';
        echo 'Created buckets:';
        nats kv list;
        echo '';
        echo 'Sample verification:';
        echo 'Administrators group metadata (bucket 550e8400-e29b-41d4-a716-446655440000):';
        nats kv get 550e8400-e29b-41d4-a716-446655440000 metadata;
        echo '';
        echo 'Developers group members (bucket 660e8400-e29b-41d4-a716-446655440001):';
        nats kv ls 660e8400-e29b-41d4-a716-446655440001 | grep members;
        echo '';
        echo 'User group assignments (default bucket):';
        nats kv get permit-groups-default users.234e5678-e89b-12d3-a456-426614174001.groups;
        echo '';
        echo 'Setup complete - ready for bucket-per-group UUID testing';
        echo 'Architecture: Each group UUID is its own NATS bucket containing that groups metadata, members, and permissions';
        echo 'User group assignments stored in default bucket since they span multiple groups';
      "
    networks:
      - nats-net

  # OPA with NATS store plugin
  opa:
    build:
      context: ../../
      dockerfile: examples/handledpaths/Dockerfile
    container_name: opa-server
    depends_on:
      nats:
        condition: service_healthy
      nats-setup:
        condition: service_completed_successfully
    ports:
      - "8181:8181"
    volumes:
      - ./config.yaml:/config/config.yaml
      - ./rego:/policies
    environment:
      - NATS_URL=nats://nats:4222
    networks:
      - nats-net

volumes:
  nats_data:
    driver: local

networks:
  nats-net:
    driver: bridge 